### PR TITLE
Add localization/vietnamese

### PR DESCRIPTION
**Pull request by josmrztranslator**
add localization/vietnamese | code: [vi-VN] to 5 files:
+ gamemodes\zombieshelterv2\gamemode\shared\shared_languages.lua
+ gamemodes\zombieshelterv2\gamemode\skill_info\skill_combat.lua
+ gamemodes\zombieshelterv2\gamemode\skill_info\skill_engineer.lua
+ gamemodes\zombieshelterv2\gamemode\skill_info\skill_survival.lua
+ resource\localization\vi-VN\zshelter_server_settings.properties

### CODE REVIEW

**Comment by NovaDiablox** [comment]
Thank you a lot for the translation! Resolve the conflicts and please change ["vi-VN"] to ["vi"] using CTRL + F and Replace All. Vietnamese language code is "vi" according to https://wiki.facepunch.com/gmod/Addon_Localization#supportedlanguages . Same goes for file name for properties directory.
"resource\localization\vi\zshelter_server_settings.properties" is the correct one.

**Comment by NovaDiablox** [comment]
And add yourself to Credits in README.

**Comment by josmrztranslator** [comment]
> Thank you a lot for the translation! Resolve the conflicts and please change ["vi-VN"] to ["vi"] using CTRL + F and Replace All. Vietnamese language code is "vi" according to https://wiki.facepunch.com/gmod/Addon_Localization#supportedlanguages . Same goes for file name for properties directory. "resource\localization\vi\zshelter_server_settings.properties" is the correct one.

**Comment by NovaDiablox** [comment]
Thanks for the translation! @Meiryi will update it soon!

**Comment by josmrztranslator** [comment]
> Thank you a lot for the translation! Resolve the conflicts and please change ["vi-VN"] to ["vi"] using CTRL + F and Replace All. Vietnamese language code is "vi" according to https://wiki.facepunch.com/gmod/Addon_Localization#supportedlanguages . Same goes for file name for properties directory. "resource\localization\vi\zshelter_server_settings.properties" is the correct one.

all done

**Comment by NovaDiablox** [comment]
> > Thank you a lot for the translation! Resolve the conflicts and please change ["vi-VN"] to ["vi"] using CTRL + F and Replace All. Vietnamese language code is "vi" according to https://wiki.facepunch.com/gmod/Addon_Localization#supportedlanguages . Same goes for file name for properties directory. "resource\localization\vi\zshelter_server_settings.properties" is the correct one.
> 
> all done

Great! @Meiryi will merge it when he is available.

**Pull request merged**
