### PR TITLE
Camouflage Tower

### PR DESCRIPTION
**Pull request by Hiccup1337**

### CODE REVIEW

**Comment by Hiccup1337** [comment]
I forgot to add it to building config, can you add it for me?

**Comment by Meiryi** [comment]
This tower will be scrapped, because there's no point to keep it since the sniper mutations are gone

**Comment by Hiccup1337** [comment]
That's fucking bullshit, you can't just merged it can said oh I don't want to use it, why did you merged it at first place then?
You're basically stealing other people's work

**Comment by Meiryi** [comment]
I reverted the changes, now fuckoff

**Pull request merged**
